sudo: false

language: php

php:
    - 5.4
    - 5.5
    - 5.6

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

  - vendor/bin/tester tests -p php
  - vendor/bin/phpcs src --standard=codestyle.xml -n

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

git:
    depth: 5

cache:
    directories:
        - $HOME/.composer/cache