sudo: false

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer self-update

before_script:
  - composer update --no-interaction --dev

script:
    - ./vendor/nette/tester/Tester/tester tests/
    - ./vendor/squizlabs/php_codesniffer/scripts/phpcs ./src --standard=codestyle.xml -n

git:
    depth: 5